services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev_glucodose_core_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  ollama:
    build:
      context: ./docker/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - IA_MODEL=${IA_MODEL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
      - ollama
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./wait-for-it.sh:/app/wait-for-it.sh
      - ./.env.production:/app/.env.production
    command:
      ['/bin/sh', '-c', '/app/wait-for-it.sh db:5432 ollama:11434 pnpm start']

volumes:
  pgdata:
  ollama_data:
