services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev_glucodose_core_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://0.0.0.0:11434
      - IA_MODEL=${IA_MODEL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "ollama serve && echo '✅ Modelo ${IA_MODEL} listo. Iniciando servidor...' && echo '⏳ Descargando modelo ${IA_MODEL} ...' && ollama pull ${IA_MODEL}"

  app:
    build: .
    depends_on:
      - db
      - ollama
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./wait-for-it.sh:/app/wait-for-it.sh
      - ./.env.production:/app/.env.production

volumes:
  pgdata:
  ollama_data:
